uncategorized:
  curated_home_design:
     default: curated_home_blog
     client: true
  curated_home_title:
    default: "Banksia dentata"
    client: true
  curated_home_intro:
    default: "commonly known as the tropical banksia, is a species of tree in the genus Banksia. It occurs across northern Australia, southern New Guinea and the Aru Islands. Growing as a gnarled tree to 7 m (23 ft) high, it has large green leaves up to 22 cm (8.7 in) long with toothed margins. The cylindrical yellow flower spikes, up to 13 cm (5 in) high, appear over the cooler months, attracting honeyeaters, sunbirds, the sugar glider and a variety of insects."
    client: true